backend:
  name: github
  repo: vicradon/regards-n-stuff
# backend:
#   name: test-repo
media_folder: static/assets
public_folder: assets
collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/markdown-posts/post1.md"
        label: "First Post"
        name: "post1"
        fields:
          - { label: "path", name: "path", widget: "string"}
          - { label: "title", name: "title", widget: "text"}
          - { label: "date", name: "date", widget: "datetime"}
      - file: "src/markdown-posts/post2.md"
        label: "Second Post"
        name: "post2"
        fields:
          - { label: "path", name: "path", widget: "string"}
          - { label: "title", name: "title", widget: "text"}
          - { label: "date", name: "date", widget: "datetime"}